// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.northwind.model;

import io.springlets.format.EntityFormat;
import org.springframework.roo.northwind.model.ShipperPhoneFormBean;

privileged aspect ShipperPhoneFormBean_Roo_DTO {
    
    declare @type: ShipperPhoneFormBean: @EntityFormat;
    
}
