// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.northwind.model.dod;

import org.springframework.beans.factory.annotation.Configurable;
import org.springframework.roo.northwind.model.dod.PartyDataOnDemand;

privileged aspect PartyDataOnDemand_Roo_Configurable {
    
    declare @type: PartyDataOnDemand: @Configurable;
    
}
